import type { Metadata } from 'next'
import './globals.css'
import type { Session } from 'next-auth'
import AuthCheck from './auth/AuthCheck'
import { Providers } from '@/providers/providers'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    <html lang='en'>
      <body>
        <Providers session={session}>
          <div>
            <AuthCheck />
            <main className='flex w-screen h-screen font-inter light'>
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}

