import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
import 'ui/global.css'
import type { Session } from 'next-auth'
import AuthCheck from './auth/AuthCheck'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    <html lang='en'>
      <body>
        <Providers session={session}>
          <AuthCheck />
          <main className='w-screen h-screen font-inter light'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
